export const theme = {
  colors: {
    white: '#fff',
    midWhite: '#EFF5FB',
    yellow: '#FFCA3A',
    blue: '#011476',
    lightBlue: '#0582CA',
    brown: '#69140E',
    grey: '#707070',
    black: '#000',
    lightPurple: '#D8DCFF',
    green: '#49E22D',
    deepPurple: '#11072C',
  },
  fonts: {
    mainFont: '"Montserrat", sans-serif',
    headerFont: '"Cinzel", serif',
    brandingFont: '"Hahmlet", serif',
    secondaryHeaderFont: '"Gentium Book Basic", serif',
    codeFont: '"Share Tech Mono", monospace',
  },
  fontSize: {
    xxl: '5rem',
    xl: '4.2rem',
    l: '3rem',
    lm: '1.8rem',
    m: '1.6rem',
    s: '1.4rem',
  },
};
